on:
  release:
    types:
      - published

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX64
          - StandaloneWindows64
          - StandaloneLinux64

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}

      - uses: game-ci/unity-builder@v4
        with:
          projectPath: .
          unityVersion: 2022.3.9f1
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: GameClient

      - uses: actions/upload-artifact@v3
        with:
          name: gameclient-${{ matrix.targetPlatform }}-${{ github.sha }}
          path: build/

  upload-to-release:
    needs:
      - build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - StandaloneLinux64
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: gameclient-${{ matrix.targetPlatform }}-${{ github.sha }}
          path: bin

      - run: |
          cp CHANGELOG.md LICENSE README.md bin/

      - name: Pack artifact (Windows)
        if: contains(matrix.targetPlatform, 'Windows')
        run: |
          cd bin
          zip -r ../gameclient-${{ matrix.targetPlatform }}.zip *
          cd ..

      - name: Pack artifact (Others)
        if: contains(matrix.targetPlatform, 'Windows') == false
        run: |
          cd bin
          tar -czvf ../gameclient-${{ matrix.targetPlatform }}.tar.gz *
          cd ..

      - name: Upload artifact to release (Windows)
        if: contains(matrix.targetPlatform, 'Windows')
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          files: |
            gameclient-${{ matrix.targetPlatform }}.zip

      - name: Upload artifact to release (Others)
        if: contains(matrix.targetPlatform, 'Windows') == false
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          files: |
            gameclient-${{ matrix.targetPlatform }}.tar.gz
